"""Lista AUTORITATIVA de codigos de assunto do ramo DIREITO TRIBUTARIO (TPU/CNJ).

Substitui a triagem por palavra-chave no NOME do assunto por uma checagem de
CODIGO contra a Tabela Processual Unificada (TPU) de Assuntos do CNJ.

FONTE DOS CODIGOS (extraidos em 2026-06):
  - SGT/CNJ - Sistema de Gestao de Tabelas Processuais Unificadas.
    SOAP WS publico: https://www.cnj.jus.br/sgt/sgt_ws.php?wsdl
    Metodo pesquisarItemPublicoWS (tipoTabela="A") devolve o dump completo de
    assuntos com cod_item + cod_item_pai; getStringPaisItemPublicoWS confirma a
    hierarquia.
    Consulta publica (humana):
    https://www.cnj.jus.br/sgt/consulta_publica_assuntos.php
  - No RAIZ do ramo: codigo 14 = "DIREITO TRIBUTARIO" (confirmado: o pai de
    "Credito Tributario" (5986) e 14, e 14 e ramo de topo). Os codigos abaixo
    sao TODOS os descendentes de 14: Impostos, Taxas, Emprestimos Compulsorios,
    Obrigacao/Credito Tributario, Divida Ativa/Execucao Fiscal, Processo/
    Procedimentos Fiscais, Contribuicoes (PIS/COFINS/CSLL/previdenciarias),
    Regimes Especiais de Tributacao, etc.
  - Validacao cruzada via API DataJud (api_publica_trf4): os pares codigo->nome
    reais retornados pela API batem com a arvore (PIS, Cofins, IRPJ, CSLL,
    Suspensao da Exigibilidade, CND, Divida Ativa, Compensacao, 1/3 de ferias,
    IPI, Seguro Acidentes do Trabalho, Parcelamento, Credito Tributario...).

NAO inclui assuntos so "parecidos" que ficam fora do ramo 14 (ex.: 10394
"Divida Ativa nao-tributaria"; crimes contra a ordem tributaria, no ramo Penal).
"""
from __future__ import annotations

import re

NOMES: dict[int, str] = {
    5913: "Limitações ao Poder de Tributar",
    5914: "Imunidade",
    5915: "Isenção",
    5916: "Impostos",
    5917: "IRPF/Imposto de Renda de Pessoa Física",
    5918: "Incidência sobre PDV",
    5919: "Incidência sobre Aposentadoria",
    5920: "Incidência sobre Aplicações Financeiras",
    5921: "Incidência sobre Licença-Prêmio/Abono/Indenização",
    5922: "Retido na fonte",
    5923: "Incidência sobre Férias Compensadas",
    5924: "Incidência sobre Proventos de Previdência Privada",
    5925: "Incidência sobre Participação nos Lucros",
    5926: "Incidência sobre Lucro Imobiliário",
    5927: "Incidência sobre 1/3 de férias (art. 7º, XVII da CF)",
    5928: "Incidência sobre 13° Salário",
    5929: "Incidência sobre Função Comissionada",
    5930: "Incidência sobre Hora Extra",
    5931: "Incidência decorrente de Desligamento de Plano de Previdência Privada",
    5932: "Incidência decorrente de Liquidação de Entidade de Previdência Privada",
    5933: "IRPJ/Imposto de Renda de Pessoa Jurídica",
    5934: "Microempresa",
    5935: "Demonstrações Financeiras (DCTF)",
    5936: "Incidência sobre Aplicações Financeiras",
    5937: "Retido na fonte",
    5938: "Incidência sobre Lucro",
    5939: "Cooperativa",
    5940: "Compensação de Prejuízos",
    5941: "II/ Imposto sobre Importação",
    5942: "Importação de bens usados",
    5943: "Drawback",
    5944: "IE/ Imposto sobre Exportação",
    5945: "IPI/ Imposto sobre Produtos Industrializados",
    5946: "ICMS/ Imposto sobre Circulação de Mercadorias",
    5947: "ICMS/Importação",
    5948: "IOC/IOF Imposto sobre operações de crédito, câmbio e seguro, ou relativas a títulos ou valores mobiliários",
    5949: "Incidência sobre Ações de Companhias Abertas",
    5950: "ITR/ Imposto Territorial Rural",
    5951: "ISS/ Imposto sobre Serviços",
    5952: "IPTU/ Imposto Predial e Territorial Urbano",
    5953: "IPVA - Imposto Sobre Propriedade de Veículos Automotores",
    5954: "ITBI - Imposto de Transmissão Intervivos de Bens Móveis e Imóveis",
    5955: "ITCD - Imposto de Transmissão Causa Mortis",
    5956: "Taxas",
    5957: "Federais",
    5958: "Taxa Anual por Hectare",
    5959: "Taxa de Armazenamento",
    5960: "Taxa de Despacho Aduaneiro",
    5961: "Taxa de Exploração Mineral",
    5962: "Taxa de Fiscalização Ambiental",
    5963: "Taxa de Guia de Importação",
    5964: "Taxa de Licença de Importação",
    5965: "Taxa de Melhoramento de Portos",
    5966: "Taxa de Permanência",
    5967: "Taxa de Saúde Suplementar",
    5968: "Taxa de Fiscalização da Comissão de Valores Mobiliários",
    5969: "Taxa Judiciária",
    5970: "Taxa de Aferição de Equipamentos de Metrologia",
    5971: "Estaduais",
    5972: "Municipais",
    5973: "Empréstimos Compulsórios",
    5974: "Aquisição de veículos automotores",
    5975: "Aquisição de combustíveis",
    5976: "Aquisição de passagens e moedas - Viagem Exterior",
    5977: "Energia Elétrica",
    5978: "Obrigação Tributária",
    5979: "Responsabilidade tributária",
    5980: "Responsabilidade Tributária do Sócio-Gerente / Diretor / Representante",
    5981: "Substituição Tributária",
    5982: "DIMOB/Declaração de Informações sobre Atividades Imobilíárias",
    5983: "CNPJ/Cadastro Nacional de Pessoas Jurídicas",
    5984: "CPF/Cadastro de Pessoas Físicas",
    5985: "Obrigação Acessória",
    5986: "Crédito Tributário",
    5987: "Suspensão da Exigibilidade",
    5988: "Carta de fiança",
    5989: "Parcelamento",
    5990: "Extinção do Crédito Tributário",
    5991: "Compensação com Apólices da Dívida Pública",
    5992: "Prescrição",
    5993: "Decadência",
    5994: "Compensação",
    5995: "TDA/Títulos da Dívida Agrária",
    5996: "Anistia",
    5997: "Denúncia espontânea",
    5998: "Lançamento",
    5999: "CND/Certidão Negativa de Débito",
    6000: "Expedição de CND",
    6001: "Expedição de Certidão Positiva de Débito com Efeito de Negativa",
    6002: "Certificado de Regularidade - FGTS",
    6003: "Incentivos fiscais",
    6004: "Anulação de Débito Fiscal",
    6005: "Juros/Correção Monetária",
    6006: "Prazo de Recolhimento",
    6007: "Repetição de indébito",
    6008: "Base de Cálculo",
    6009: "Crédito Prêmio",
    6010: "Crédito Presumido",
    6011: "Fato Gerador/Incidência",
    6012: "Alíquota",
    6013: "Alíquota Zero",
    6014: "Alíquota Progressiva",
    6015: "Índice da Alíquota",
    6016: "Creditamento",
    6017: "Dívida Ativa (Execução Fiscal)",
    6018: "Processo Administrativo Fiscal",
    6019: "Depósito Prévio ao Recurso Administrativo",
    6020: "Arrolamento de Bens",
    6021: "Procedimentos Fiscais",
    6022: "Sigilo Fiscal",
    6023: "Utilização de Dados Relativos à CPMF para Fins de Fiscalização",
    6024: "Liberação de mercadorias",
    6025: "Levantamento de depósito",
    6026: "Cadastro de Inadimplentes - CADIN/SPC/SERASA/SIAFI/CAUC",
    6027: "Autorização para Impressão de Documentos Fiscais - AIDF",
    6028: "Liberação de Veículo Apreendido",
    6029: "Perdimento de Bens",
    6030: "GATT - &quot;Acordo Geral sobre Tarifas e Comércio&quot;",
    6031: "Contribuições",
    6032: "Contribuições de Melhoria",
    6033: "Contribuições Sociais",
    6034: "Finsocial",
    6035: "Cofins",
    6036: "Contribuição Social sobre o Lucro Líquido",
    6037: "Salário-Educação",
    6038: "Seguro Acidentes do Trabalho",
    6039: "PIS",
    6040: "Funrural",
    6041: "Contribuição INCRA",
    6042: "PASEP",
    6043: "Construção Civil",
    6044: "Contribuições Corporativas",
    6045: "Contribuições para o SEBRAE, SESC, SENAC, SENAI e outros",
    6046: "Conselhos Regionais e Afins (Anuidade)",
    6047: "Contribuição Sindical",
    6048: "Contribuições Previdenciárias",
    6049: "Servidores Ativos",
    6050: "Servidores Inativos",
    6051: "Mandato Eletivo/Lei 9.506/97",
    6052: "Aposentadoria/Retorno aoTrabalho",
    6053: "Cargo em Comissão",
    6054: "Tempo de Serviço Urbano/Contribuições não Recolhidas",
    6055: "Tempo de Serviço Rural/Contribuições não Recolhidas",
    6056: "Gratificação Natalina/13º Salário",
    6057: "Produção Agropecuária",
    6058: "Indenização Trabalhista",
    6059: "Reembolso auxílio-creche",
    6060: "Contribuição sobre a folha de salários",
    6061: "Devolução de contribuições previdenciárias pagas além do teto",
    6062: "1/3 de férias",
    6063: "Auxílio-Alimentação",
    6064: "Custeio de Assistência Médica",
    6065: "Hora Extra",
    6066: "Massa Falida- Recolhimento",
    6067: "Nota Fiscal ou Fatura",
    6068: "Salário-Maternidade",
    6069: "Contribuição sobre Nota Fiscal de Execução de Serviços",
    6070: "Contribuição de Autônomos, Empresários (Pró-labore) e Facultativos",
    6071: "Contribuições Especiais",
    6072: "FNT/Fundo Nacional de Telecomunicações",
    6073: "ATP/Adicional de Tarifa Portuária",
    6074: "AITP/Adicional de Indenização do Trabalhador Portuário Avulso",
    6075: "Adicional de Tarifa Aeroportuária",
    6076: "AFRMM/Adicional ao Frete para Renovação da Marinha Mercante",
    6077: "FUNDEB/FUNDEF/Fundo de Manutenção e Desenvolvimento do Ensino Fundamental e de Valorização do Magistério",
    6078: "Seguro Apagão (Lei 10.438/02)",
    6079: "Contribuição sobre licença de uso ou transferência de tecnologia",
    6080: "Contribuição de Intervenção no Domínio Econômico (CIDE)",
    6081: "FUNDAF/Fundo Especial de Desenvolvimento e Aperfeiçoamento das Atividades de Fiscalização",
    6082: "FUSEX/FUNSA/FUSMA/Fundo de Saúde das Forças Armadas",
    6083: "Contribuição de Iluminação Pública",
    6084: "IUEE/Imposto Único sobre Energia Elétrica",
    6085: "FGTS/Fundo de Garantia Por Tempo de Serviço",
    6086: "Contribuição sobre Açúcar e Álcool",
    6087: "CPMF/Contribuição Provisória sobre Movimentação Financeira",
    6088: "Discriminação Tributária MERCOSUL",
    6089: "Regimes Especiais de Tributação",
    6090: "REFIS/Programa de Recuperação Fiscal",
    6091: "PAES/Parcelamento Especial",
    6092: "SIMPLES",
    6093: "Super SIMPLES",
    10527: "Livros / Jornais / Periódicos",
    10528: "Entidades Sem Fins Lucrativos",
    10529: "Partidos Políticos",
    10530: "Imunidade Recíproca",
    10531: "ICMS / Incidência Sobre o Ativo Fixo",
    10532: "Incidência sobre Auxílio-condução",
    10533: "Incidência sobre Auxílio-creche",
    10534: "Taxa de Limpeza Pública",
    10535: "Taxa de Iluminação Pública",
    10536: "Taxa de Coleta de Lixo",
    10537: "Taxa de Prevenção e Combate a Incêndio",
    10538: "Taxa de Licenciamento de Estabelecimento",
    10539: "Capacidade Tributária",
    10540: "Competência Tributária",
    10543: "Depósito Judicial",
    10544: "Constitucionalidade do artigo 4º da LC 118/05",
    10545: "Constitucionalidade do artigo 46 da Lei 8212/91",
    10546: "Suspensão",
    10547: "Interrupção",
    10548: "Decretação de Ofício",
    10549: "Arquivamento Administrativo - Crédito de Pequeno Valor",
    10550: "Despacho de Citação",
    10551: "Constitucionalidade do artigo 45 da Lei 8212/91",
    10556: "Exclusão - ICMS",
    10557: "Exclusão - IPI",
    10558: "Exclusão - Receitas Provenientes de Exportação",
    10559: "Cálculo de ICMS &quot;por dentro&quot;",
    10560: "Quebra de Sigilo Bancário",
    10561: "PIS - Importação",
    10562: "COFINS - Importação",
    10563: "Compensação de Prejuízo",
    10565: "Contribuição Sindical Rural",
    10661: "Incidência sobre Abono de Permanência",
    10689: "Correção da Tabela",
    10690: "IPMF - Imposto Provisório sobre Movimentação Financeira",
    10871: "Não Cumulatividade",
    10872: "Nao Cumulatividade",
    10873: "Não Cumulatividade",
    10874: "Não Cumulatividade",
    10887: "Ausência de Cobrança Administrativa Prévia",
    10903: "Incidência sobre desconto incondicional",
    10922: "Cobrança de Multa Moratória de Massa Falida",
    10923: "Cobrança de Juros Moratórios de Massa Falida",
    10947: "Princípio da Seletividade",
    10959: "Exclusão - Receitas Transferidas a outras Pessoas Jurídicas",
    14883: "Fundo de Saúde do Exército - FUSEX",
    14884: "Fundo de Saúde do Exército - FUSEX",
    14885: "Fundo de Saúde da Aeronáutica - FUNSA",
    14886: "Fundo de Saúde da Marinha - FUSMA",
    14887: "Adicional de Plantão Hospitalar",
    14888: "Indenização a Anistiados Políticos, Civis ou Militares",
    14889: "Sobre a Receita Bruta (Substitutiva)",
    14890: "Cooperativa",
    14891: "Concessionárias de Veículos",
    14892: "Equiparação com Instituições Financeiras",
    14893: "Locação de Bem Móvel e Imóvel",
    14894: "Regime Monofásico",
    14895: "Cooperativa",
    14896: "Concessionárias de Veículos",
    14897: "Locação de Bem Móvel e Imóvel",
    14898: "Regime Monofásico",
    14899: "Cofins",
    14900: "PIS",
    14946: "PIS - Cofins",
    14947: "Cofins",
    14948: "PIS",
    14949: "PIS - Cofins",
    14950: "Pagamento",
    14951: "Honorários Advocatícios",
    14952: "Encargo de 20%",
    14953: "Adesão a Programa de Parcelamento de Débito",
    14962: "Isenção sobre Bens Contidos em Remessas Postais Internacionais",
    14963: "Sobre Aquisição de Bens/Veículos",
    14964: "Veículos",
    14965: "Motorista de Táxi",
    14966: "Pessoa Portadora de Deficiência",
    14967: "Sobre Importação de Bens/Veículos",
    14986: "Admissão Temporária",
    14987: "Veículos - Uso Próprio",
    14988: "Incidência sobre Ajuda de Custo",
    14989: "Atividade Parlamentar",
    14992: "Incidência sobre Benefícios Pagos Acumuladamente",
    14993: "Incidência sobre Serviços Técnicos Prestados a Organismos Internacionais (PNUD/UNESCO/ONU)",
    14994: "Incidência sobre Indenização a Anistiados Políticos, Civis ou Militares",
    14995: "Incidência sobre Indenização por Rescisão de Contrato de Trabalho",
    14996: "Redução de Alíquota IR/CSLL - Serviços Hospitalares",
    15001: "Áreas de Livre Comércio - ZFM e/ou Outras",
    15002: "Operações Comerciais",
    15003: "Saída Temporária - Mercadorias",
    15004: "Saída Temporária - Veículos",
    15005: "Multa por Descumprimento de Obrigação Acessória",
    15006: "Infração à Legislação Previdenciária",
    15007: "Infração à Legislação Trabalhista",
    15051: "Reintegra",
    15052: "Taxa de Fiscalização de Instalação",
    15053: "Taxa de Fiscalização de Funcionamento",
    15054: "Taxa de Fiscalização de Vigilância Sanitária",
    15055: "Taxa de Serviço Administrativo - TSA",
    15480: "Isenção por Doença ou Acidente em Serviço",
    15722: "IBS - Imposto sobre Bens e Serviços",
    15723: "CBS - Contribuição sobre Bens e Serviços",
}


# Conjunto autoritativo: todos os descendentes do no 14 (DIREITO TRIBUTARIO).
CODIGOS_TRIBUTARIOS: set[int] = {14, *NOMES}

# Rede de seguranca: se um assunto vier com codigo novo/ausente na TPU baixada,
# ainda detecta por palavra-chave no nome (mesma cobertura do filtro antigo).
_KW_TRIBUTARIO = re.compile(
    r"trib|pis|cofins|icms|iss\b|ipi|iof|irpj|irpf|csll|imposto|contribui|fiscal|"
    r"al[íi]quota|exigibilidade|cnd|certid[ãa]o negativa|ind[ée]bito|compensa|"
    r"previden|sal[áa]rio|folha|fgts|simples nacional|selic|refis|parcelamento|"
    r"imunidade|isen[çc][ãa]o|cr[ée]dito tribut|creditamento|cr[ée]dito presumido|"
    r"difal|itr|taxa|seguro acidente|sat\b|rat\b|fap\b|terceiros|sistema s|"
    r"d[íi]vida ativa|execu[çc][ãa]o fiscal|imposto de renda|sal[áa]rio-educa",
    re.I,
)
_KW_NAO_TRIBUTARIO = re.compile(r"n[ãa]o[- ]tribut", re.I)


def eh_tributario(assuntos: list[dict]) -> bool:
    """True se algum assunto pertence ao ramo DIREITO TRIBUTARIO (TPU/CNJ).

    `assuntos`: lista no formato da API DataJud, cada item {"codigo": int,
    "nome": str}. Decide primeiro pelo CODIGO (autoritativo); se nenhum codigo
    casar, cai no fallback por palavra-chave no NOME (robustez p/ codigos novos
    ou registros sem codigo).
    """
    for a in assuntos or []:
        cod = a.get("codigo")
        try:
            if cod is not None and int(cod) in CODIGOS_TRIBUTARIOS:
                return True
        except (TypeError, ValueError):
            pass
    for a in assuntos or []:
        nome = a.get("nome") or ""
        if _KW_NAO_TRIBUTARIO.search(nome):
            continue
        if _KW_TRIBUTARIO.search(nome):
            return True
    return False
